
drop table if exists BLUE_ACCOUNT;
drop table if exists BLUE_PAYMENT;
create table BLUE_ACCOUNT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, email varchar(255) not null, mobile varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table BLUE_PAYMENT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, amount decimal(19,2) not null, comments varchar(255) not null, dueDate datetime(6) not null, issueDate datetime(6) not null, reference varchar(255) not null, primary key (id)) engine=InnoDB;
drop table if exists BLUE_ACCOUNT;
drop table if exists BLUE_PAYMENT;
create table BLUE_ACCOUNT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, email varchar(255) not null, mobile varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table BLUE_PAYMENT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, amount decimal(19,2) not null, comments varchar(255), dueDate date not null, issueDate date not null, reference varchar(255) not null, primary key (id)) engine=InnoDB;
drop table if exists BLUE_ACCOUNT;
drop table if exists BLUE_PAYMENT;
create table BLUE_ACCOUNT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, email varchar(255) not null, mobile varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table BLUE_PAYMENT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, amount decimal(19,2) not null, comments varchar(255), dueDate date not null, isPaid bit not null, issueDate date not null, reference varchar(255) not null, primary key (id)) engine=InnoDB;
drop table if exists BLUE_ACCOUNT;
drop table if exists BLUE_PAYMENT;
create table BLUE_ACCOUNT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, email varchar(255) not null, mobile varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table BLUE_PAYMENT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, amount decimal(19,2) not null, comments varchar(255), dueDate date not null, issueDate date not null, reference varchar(255) not null, status integer, primary key (id)) engine=InnoDB;
drop table if exists BLUE_ACCOUNT;
drop table if exists BLUE_PAYMENT;
create table BLUE_ACCOUNT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, email varchar(255) not null, mobile varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table BLUE_PAYMENT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, amount decimal(19,2) not null, comments varchar(255), dueDate datetime(6) not null, issueDate datetime(6) not null, reference varchar(255) not null, status integer, primary key (id)) engine=InnoDB;
drop table if exists BLUE_ACCOUNT;
drop table if exists BLUE_PAYMENT;
create table BLUE_ACCOUNT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, email varchar(255) not null, mobile varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table BLUE_PAYMENT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, amount decimal(19,2) not null, comments varchar(255), dueDate date not null, issueDate datetime(6) not null, reference varchar(255) not null, status integer, primary key (id)) engine=InnoDB;
drop table if exists BLUE_ACCOUNT;
drop table if exists BLUE_PAYMENT;
create table BLUE_ACCOUNT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, email varchar(255) not null, mobile varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table BLUE_PAYMENT (id varchar(255) not null, createdOn datetime(6), updatedOn datetime(6), version integer, amount decimal(19,2) not null, comments varchar(255), dueDate date not null, issueDate datetime(6) not null, reference varchar(255) not null, status varchar(255), primary key (id)) engine=InnoDB;
